apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: registry
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitnami/minio
    targetRevision: 14.10.1
    helm:
      parameters:
        - name: auth.rootUser
          value: admin
        - name: auth.rootPassword
          value: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
