apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: registry
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: latest
