apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  labels:
    app.kubernetes.io/instance: mlflow-database
  annotations:
    # keep the database after base is deleted
    argocd.argoproj.io/sync-options: Delete=false
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: postgresql
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 16.3.4
    helm:
      releaseName: bitnami/postgresql
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
info:
  - description: 'Managed PostgreSQL database'
    icon: 'https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png'
    displayName: 'PostgreSQL'
    maintainers:
      - name: Bitnami
syncPolicy:
  retry:
    limit: 1
