apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-database
  namespace: registry
  labels:
    app.kubernetes.io/instance: mlflow-database
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
