apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mahdikhashan/jku-cloud-computing
    targetRevision: main # branch
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: apps/base
      repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: main
    - path: namespaces
      repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: main
    - path: repositories
      repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: main
