apiVersion: source.argoproj.io/v1alpha1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  url: https://charts.bitnami.com/bitnami
