{{ if .Values.certManagerKubeflowIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeflow-self-signing-issuer
spec:
  {{ .Values.certManagerKubeflowIssuer.spec | toYaml | indent 2 }}
{{- end -}}