{{ if .Values.istioNamespace.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{ .Values.istioNamespace.spec | toYaml | indent 2 }}
{{- end -}}