apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: registry
  labels:
    app.kubernetes.io/instance: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: community-charts/mlflow
    targetRevision: 0.8.2
    helm:
      valueFiles:
        - values.yaml
