apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-ingress
  namespace: ingress-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: 24.144.65.73
    - http:
        paths:
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ingress-namespace
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
  ports:
    - port: 3000
