backendStore:
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: "mysql-instance1.cg034hpkmmjt.eu-central-1.rds.amazonaws.com"
    port: 5432
    database: "mlflow_db"
    user: "mlflow_user"
    password: "mlflow_password"
artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: admin
    awsSecretAccessKey: admin
    MLFLOW_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
serviceMonitor:
  enabled: true
