backendStore:
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: "postgresql.registry.svc.cluster.local"
    port: 5432
    database: "mlflow_db"
    user: "mlflow_user"
    password: "mlflow_password"
artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: admin
    awsSecretAccessKey: admin
    MLFLOW_S3_ENDPOINT_URL: minio.registry.svc.cluster.local
serviceMonitor:
  enabled: true
