debug: false

certManager:
  enabled: true
  spec:
    project: default
    source:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

certManagerKubeflowIssuer:
  enabled: true
  spec:
    selfSigned: { }

kubeflowNamespace:
  enabled: true
  spec:
    project: default
    source:
      path: common/kubeflow-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: kubeflow
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

centralDashboard:
  enabled: true
  spec:
    project: default
    source:
      path: apps/centraldashboard/overlays/oauth2-proxy
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
