debug: false

certManager:
  enabled: true
  spec:
    project: default
    source:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

certManagerKubeflowIssuer:
  enabled: true
  spec:
    selfSigned: { }

#centralDashboard:
#  enabled: true
#  spec:
#    project: default
#    source:
#      path: apps/centraldashboard/overlays/oauth2-proxy
#      repoURL: https://github.com/kubeflow/manifests
#      targetRevision: master
#      kustomize:
#        patches:
#          - target:
#              kind: ConfigMap
#              name: centraldashboard-config
#            patch: |-
#              - op: replace
#                path: /data/links
#                value: |
#                  {
#                    "menuLinks": [
#                      {
#                        "type": "item",
#                        "link": "/jupyter/",
#                        "text": "Notebooks",
#                        "icon": "book"
#                      },
#                      {
#                        "type": "item",
#                        "link": "/volumes/",
#                        "text": "Volumes",
#                        "icon": "device:storage"
#                      }
#                    ],
#                    "externalLinks": [ ],
#                      "quickLinks": [
#                        {
#                          "text": "Create a new Notebook server",
#                          "desc": "Notebook Servers",
#                          "link": "/jupyter/new?namespace=kubeflow"
#                        }
#                      ],
#                      "documentationItems": [
#                        {
#                          "text": "Getting Started with Kubeflow",
#                          "desc": "Get your machine-learning workflow up and running on Kubeflow",
#                          "link": "https://www.kubeflow.org/docs/started/getting-started/"
#                        }
#                      ]
#                  }
#    destination:
#      namespace: argocd
#      name: in-cluster
#    syncPolicy:
#      automated:
#        prune: true
#      syncOptions:
#        - CreateNamespace=true
#        - ServerSideApply=true
