debug: false

certManager:
  enabled: true
  spec:
    project: default
    sources:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      helm:
        releaseName: "cert-manager"
        ignoreMissingValueFiles: true
        valueFiles: [ ]
        values: |
          installCRDs: true
  destination:
    namespace: argocd
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
