debug: false

certManager:
  enabled: true
  spec:
    project: default
    sources:
      - chart: 'cert-manager'
        repoURL: https://charts.jetstack.io
        targetRevision: "1.14.3"
        helm:
          releaseName: "cert-manager"
          ignoreMissingValueFiles: true
          valueFiles: [ ]
          values: |
            installCRDs: true
    destination:
      namespace: 'cert-manager'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
