debug: false

certManager:
  enabled: true
  spec:
    project: default
    source:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

certManagerKubeflowIssuer:
  enabled: true
  spec:
    selfSigned: { }

istioBase:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/istio-crds/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: istio-system
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

istioNamespace:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/istio-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argo
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

istioInstall:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-23/istio-install/overlays/oauth2-proxy.yaml
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: istio-system
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

oauth2Proxy:
  enabled: true
  spec:
    project: default
    source:
      path: common/oauth2-proxy/overlays/m2m-dex-only/
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argo
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

kubeflowNamespace:
  enabled: true
  spec:
    project: default
    source:
      path: common/kubeflow-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: kubeflow
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

centralDashboard:
  enabled: true
  spec:
    project: default
    source:
      path: apps/centraldashboard/overlays/oauth2-proxy.yaml
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
