debug: false

certManager:
  enabled: true
  spec:
    project: default
    source:
      path: common/cert-manager/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: master
    destination:
      namespace: cert-manager
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

certManagerKubeflowIssuer:
  enabled: true
  spec:
    selfSigned: {}
  kustomize:
    labels:
      - includeSelectors: true
        pairs:
          app.kubernetes.io/component: cert-manager
          app.kubernetes.io/name: cert-manager
          kustomize.component: cert-manager
