apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mahdikhashan/jku-cloud-computing
    targetRevision: pipelines
    path: apps
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: pipelines
      path: apps/kubeflow
      #    - repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      #      targetRevision: main
      #      path: apps/monitoring/prometheus
      #    - repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      #      targetRevision: main
      #      path: apps/monitoring/grafana
    - repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: pipelines
      path: apps/namespaces
    - repoURL: https://github.com/mahdikhashan/jku-cloud-computing
      targetRevision: pipelines
      path: apps/registry/mlflow
