apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-installer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mahdikhashan/jku-cloud-computing'
    targetRevision: main
    path: apps/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: serving
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
