name: Build Inference Images
on:
  push:
    paths:
      - inference/api/**
      - inference/ui/**
    branches:
      - main
jobs:
  build:
    name: push docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to dockerhub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: build api image
        run: |
          cd inference/api
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-service:latest .
      - name: build ui image
        run: |
          cd inference/ui
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ui-service:latest .
      - name: push the images to docker hub
        id: push-docker-image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/api-service:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/ui-service:latest
